# Matrix Reductions
---
Técnicas para aprender reduções de matrizes, pegando matrizes de ordens grandes e obtendo uma pelo menos uma ordem menor que a anterior

In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()
x = tf.constant([[1, 2, 3], [3, 2, 1], [-1, -2, -3]])
boolean_tensor = tf.constant([[True, False, True], [False, False, True], [True, False, False]])

In [2]:
tf.reduce_prod(x, reduction_indices=1).eval()

array([ 6,  6, -6], dtype=int32)

In [3]:
tf.reduce_min(x, reduction_indices=1).eval()

array([ 1,  1, -3], dtype=int32)

In [4]:
tf.reduce_max(x, reduction_indices=1).eval()

array([ 3,  3, -1], dtype=int32)

In [5]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([ 2,  2, -2], dtype=int32)

In [6]:
tf.reduce_all(boolean_tensor, reduction_indices=1).eval()

array([False, False, False])

In [7]:
tf.reduce_any(boolean_tensor, reduction_indices=1).eval()

array([ True,  True,  True])