# Tensor Shape Transformations
---
Transformações que alteram o shape dos tensores, também adicionando e removendo dimensões.

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [4]:
x = tf.constant([[2, 5, 3, 5],
                 [0, 3, -2, 5],
                 [4, 3, 5, 3],
                 [6, 1, 4, 0]])

In [5]:
tf.shape(x).eval()

array([4, 4], dtype=int32)

In [6]:
tf.size(x).eval()

16

In [7]:
tf.rank(x).eval()

2

In [10]:
tf.reshape(x, [8, 2]).eval() #changing matrix shape, size must be the same

array([[ 2,  5],
       [ 3,  5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [11]:
tf.squeeze(x).eval() # remove dimensions of size 1

array([[ 2,  5,  3,  5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [12]:
tf.expand_dims(x, 1).eval()

array([[[ 2,  5,  3,  5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]], dtype=int32)