# Sequences
---
Trabalhando os principais métodos para se utilizar sequências e tensores.

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3, -2, 5],
                 [4, 3, 5, 3], 
                 [6, 1, 4, 0]])

In [4]:
listx = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
listy = tf.constant([4, 5, 8, 9])

In [31]:
boolx = tf.constant([[False, True], [False, True]])

In [10]:
tf.argmin(x, 1).eval() # index of minimal argument of first dimension

array([3, 2, 1, 3])

In [11]:
tf.argmax(x, 1).eval() # index of maximum argument of first dimension

array([1, 3, 2, 0])

In [32]:
tf.where(boolx).eval() # index of trues in dimension

array([[0, 1],
       [1, 1]])

In [38]:
tf.unique(listx)[0].eval() # unique elements in a list

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [42]:
tf.setdiff1d(listx, listy)[0].eval()

array([1, 2, 3, 6, 7], dtype=int32)