# Slice and Joining
---
Fatores para extrair e juntar informações relevantes acerca das matrizes trabalhadas

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
t_matrix = tf.constant([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

In [4]:
t_array = tf.constant([1, 2, 3, 4, 9, 8, 6, 5])

In [5]:
t_array2 = tf.constant([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
tf.slice(t_matrix, [1, 1], [2, 2]).eval()  # repartindo tensor 

array([[5, 6],
       [8, 9]], dtype=int32)

In [10]:
tf.split(axis=0, num_or_size_splits=2, value=t_array)  # dividindo tensor

[<tf.Tensor 'split:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split:1' shape=(4,) dtype=int32>]

In [13]:
tf.tile([1, 2], [3]).eval()  # multiplicando array

array([1, 2, 1, 2, 1, 2], dtype=int32)

In [14]:
tf.pad(t_matrix, [[0, 1], [2, 1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)