# Tensor Segmentation
---
Reduction of the tensor's size

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
seg_ids = tf.constant([0, 1, 1, 2, 2]) # Group indexes 0|1,2|3,4

In [4]:
tens1 = tf.constant([[2, 5, 3, -5], [0, 3, -2, 5], [4, 3, 4, 3], [6, 1, 4, 0], [6, 1, 4, 0]])# A sample constant matrix

In [5]:
tf.segment_sum(tens1, seg_ids).eval() # product segmentation

array([[ 2,  5,  3, -5],
       [ 4,  6,  2,  8],
       [12,  2,  8,  0]], dtype=int32)

In [6]:
tf.segment_prod(tens1, seg_ids).eval() # product segmentation

array([[ 2,  5,  3, -5],
       [ 0,  9, -8, 15],
       [36,  1, 16,  0]], dtype=int32)

In [7]:
tf.segment_min(tens1, seg_ids).eval() # min segmentation

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [8]:
tf.segment_max(tens1, seg_ids).eval() # max segmentation

array([[ 2,  5,  3, -5],
       [ 4,  3,  4,  5],
       [ 6,  1,  4,  0]], dtype=int32)

In [9]:
tf.segment_mean(tens1, seg_ids).eval() # mean segmentation

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)