# Métodos Básicos para Tensores
---
Alguns métodos básicos para a manipulação de tensores.

In [2]:
import tensorflow as tf
sess = tf.InteractiveSession()

x = tf.constant([[2, 5, 3, -5], [0, 3, -2, 5], [4, 3, 5, 3], [6, 1, 4, 0]])
y = tf.constant([[4, -7, 4, -3, 4], [6, 4, -7, 4, 7], [2, 3, 2, 1, 4], [1, 5, 5, 5, 2]])
floatx = tf.constant([[2., 5., 3., -5.], [0., 3., -2., 5.], [4., 3., 5., 3.], [6., 1., 4., 0.]])

/home/anthonylouis/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [3]:
tf.transpose(x).eval()

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]], dtype=int32)

In [4]:
tf.matmul(x, y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]], dtype=int32)

In [5]:
tf.matrix_determinant(floatx).eval()

818.0001

In [6]:
tf.matrix_inverse(floatx).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.2811736 , -0.1809291 ],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]],
      dtype=float32)

In [8]:
tf.matrix_solve(floatx, [[1], [1], [1], [1]]).eval()

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)